spring.application.name=notification-service

server.port=8080

hotel.service.base-url=http://hotel-service-h2-env-env.eba-3pkfrmiy.eu-north-1.elasticbeanstalk.com

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html