services:
  mongodb:
    image: mongo:7
    container_name: hotel-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  hotel-service:
    build: ./hotel-service
    container_name: hotel-service
    ports:
      - "8080:8080"

  comments-service:
    build: ./comments-service
    container_name: comments-service
    ports:
      - "8085:8085"
    depends_on:
      - mongodb

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8086:8086"
    depends_on:
      - hotel-service

  ai-agent-service:
    build: ./ai-agent-service
    container_name: ai-agent-service
    ports:
      - "8084:8084"
    depends_on:
      - hotel-service

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:8088"
    depends_on:
      - hotel-service
      - comments-service
      - notification-service
      - ai-agent-service

  frontend:
    build: ./frontend
    container_name: hotel-frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway

volumes:
  mongo_data: